### ISSUE TITLE
Not possible to copy a resource with "jcr:versionHistory" property. 

### ISSUE THREAD

**Issue by seanpoder** [valtech/aem-easy-content-upgrade#105]
It is not possible to copy a resource containing system properties as "jcr:versionHistory" using "doCopyResourceToRelativePath(String relativePath)".

NOTE: This might be happening for other properties as well.

<img width="1398" alt="Screenshot 2019-05-13 at 17 16 22" src="https://user-images.githubusercontent.com/40890203/57633737-3ffad400-75a4-11e9-9402-889577e1fcfe.png">

**Comment by gruberrolandvaltech** [comment]
Provide new methods to copy and move pages via page manager. We have a similar issue with doMoveResourceToRelativePath() for pages.

org.apache.sling.api.resource.PersistenceException: Unable to delete resource
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.delete(JcrResourceProvider.java:500)
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.delete(AuthenticatedResourceProvider.java:193)
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.delete(ResourceResolverControl.java:402)
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.move(ResourceResolverControl.java:628)
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.move(ResourceResolverImpl.java:1102)

**Comment by gruberrolandvaltech** [comment]
Alternative: detect if resource is a page and use page manager automatically. This might be time consuming.

**Comment by gruberrolandvaltech** [comment]
Done in https://github.com/valtech/aem-easy-content-upgrade/pull/119

**Comment by roxana-muresan** [comment]
Fixed and ready to be released in 3.1.0
