### ISSUE TITLE
Issue with AecuInstallHook on the local AEM SDK

### ISSUE THREAD

**Issue by michal-tobiasz-wttech** [valtech/aem-easy-content-upgrade#183]
I wanted to use AECU version 6.0.0 of the tool. I have an AEM project created from archetypeVersion=36 with aemVersion=cloud.
**<aem.sdk.api>2022.3.6698.20220318T233218Z-220400</aem.sdk.api>**
I have created a module based on the "examples-cloud" (https://github.com/valtech/aem-easy-content-upgrade/tree/develop/examples-cloud). Additionally, the module is added to the "all" module as embedded.
When executing the command on the local AEM SDK `mvn clean install -PautoInstallSinglePackage -PinstallHook` in the AEM logs I see an exception and groovy scripts are not executed.

Could you please suggest how to avoid this exception?

```
09.05.2022 23:29:33.342 *WARN* [OsgiInstallerImpl] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook aecu threw runtime exception.
java.lang.NullPointerException: null
	at de.valtech.aecu.core.installhook.AecuTrackerListener.onMessage(AecuTrackerListener.java:86) [de.valtech.aecu.core:6.0.0]
	at de.valtech.aecu.core.installhook.AecuTrackerListener.logMessage(AecuTrackerListener.java:139) [de.valtech.aecu.core:6.0.0]
	at de.valtech.aecu.core.installhook.AecuTrackerListener.<init>(AecuTrackerListener.java:70) [de.valtech.aecu.core:6.0.0]
	at de.valtech.aecu.core.installhook.AecuInstallHook.execute(AecuInstallHook.java:91) [de.valtech.aecu.core:6.0.0]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.execute(InstallHookProcessorImpl.java:143) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:226) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:401) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:360) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:354) [org.apache.jackrabbit.vault:3.4.0]
	at com.adobe.granite.installer.factory.packages.impl.PackageTransformer$InstallPackageTask.execute(PackageTransformer.java:350) [com.adobe.granite.installer.factory.packages:1.0.20]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:918) [org.apache.sling.installer.core:3.12.0]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:755) [org.apache.sling.installer.core:3.12.0]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:304) [org.apache.sling.installer.core:3.12.0]
	at java.base/java.lang.Thread.run(Thread.java:834)
09.05.2022 23:29:33.343 *INFO* [OsgiInstallerImpl] de.valtech.aecu.core.installhook.AecuInstallHook Executing in phase INSTALLED
09.05.2022 23:29:33.344 *WARN* [OsgiInstallerImpl] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook aecu threw runtime exception.
java.lang.NullPointerException: null
	at de.valtech.aecu.core.installhook.AecuInstallHook.getScriptsForExecution(AecuInstallHook.java:121) [de.valtech.aecu.core:6.0.0]
	at de.valtech.aecu.core.installhook.AecuInstallHook.execute(AecuInstallHook.java:99) [de.valtech.aecu.core:6.0.0]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.execute(InstallHookProcessorImpl.java:143) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:240) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:401) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:360) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:354) [org.apache.jackrabbit.vault:3.4.0]
```

**Comment by gruberrolandvaltech** [comment]
Which version of the cloud SDK is this?

**Comment by michal-tobiasz-wttech** [comment]
<aem.sdk.api>2022.3.6698.20220318T233218Z-220400</aem.sdk.api>

**Comment by gruberrolandvaltech** [comment]
I just tried with 2022.4.7138.20220427T075748Z-220401 and it works.
Do you have this issue
* when installing the AECU examples package?
* when installing your script package standalone (without the "all" one)?
* each time you install the "all" one or just sometimes?

**Comment by gruberrolandvaltech** [comment]
Does the same thing happen on a new AEM instance (installing only AECU Cloud and Cloud Examples)?

**Comment by gruberrolandvaltech** [comment]
From the log it seems that package "com.test:test.ui.aecu" installs fine with the scripts. But your package "com.test:test.ui.config" fails.
Maybe you added the hook to all your packages? Please only use it in the package that contains the scripts.

**Comment by michal-tobiasz-wttech** [comment]
The hook `installhook.aecu.class` is configured in module test.ui.aecu and second hook `installhook.actool.class` in module ui.acl
module test.ui.config doesn't have a hook.
For reference 
**pom.xml of test.ui.aecu**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.test</groupId>
        <artifactId>test</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>test.ui.aecu</artifactId>
    <packaging>content-package</packaging>
    <name>test - AECU Package</name>
    <description>AECU package for test</description>

    <build>
        <sourceDirectory>src/main/content/jcr_root</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.jackrabbit</groupId>
                <artifactId>filevault-package-maven-plugin</artifactId>
                <configuration>
                    <group>com.test</group>
                    <name>test.ui.aecu</name>
                    <properties>
                        <cloudManagerTarget>none</cloudManagerTarget>
                    </properties>
                    <packageType>application</packageType>
                    <dependencies>
                        <dependency>
                            <groupId>de.valtech.aecu</groupId>
                            <artifactId>aecu.complete.cloud</artifactId>
                        </dependency>
                    </dependencies>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.sling</groupId>
                <artifactId>htl-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>de.valtech.aecu</groupId>
            <artifactId>aecu.complete.cloud</artifactId>
            <type>zip</type>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>installHook</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.jackrabbit</groupId>
                        <artifactId>filevault-package-maven-plugin</artifactId>
                        <configuration>
                            <packageType>mixed</packageType>
                            <properties>
                                <installhook.aecu.class>de.valtech.aecu.core.installhook.AecuInstallHook</installhook.aecu.class>
                            </properties>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
```
**pom.xml of all module**
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- ====================================================================== -->
    <!-- P A R E N T  P R O J E C T  D E S C R I P T I O N                      -->
    <!-- ====================================================================== -->
    <parent>
        <groupId>com.test</groupId>
        <artifactId>test</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <!-- ====================================================================== -->
    <!-- P R O J E C T  D E S C R I P T I O N                                   -->
    <!-- ====================================================================== -->
    <artifactId>test.all</artifactId>
    <packaging>content-package</packaging>
    <name>test - All</name>
    <description>All content package for test</description>

    <!-- ====================================================================== -->
    <!-- B U I L D   D E F I N I T I O N                                        -->
    <!-- ====================================================================== -->
    <build>
        <plugins>
            <!-- ====================================================================== -->
            <!-- V A U L T   P A C K A G E   P L U G I N S                              -->
            <!-- ====================================================================== -->
            <plugin>
                <groupId>org.apache.jackrabbit</groupId>
                <artifactId>filevault-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <group>com.test</group>
                    <packageType>container</packageType>
                    <!-- skip sub package validation for now as some vendor packages like CIF apps will not pass -->
                    <skipSubPackageValidation>true</skipSubPackageValidation>
                    <allowIndexDefinitions>true</allowIndexDefinitions>
                    <embeddeds>
                        <embedded>
                            <groupId>com.test</groupId>
                            <artifactId>test.ui.apps</artifactId>
                            <type>zip</type>
                            <target>/apps/test-packages/application/install</target>
                        </embedded>
                        <embedded>
                            <groupId>com.test</groupId>
                            <artifactId>test.core</artifactId>
                            <target>/apps/test-packages/application/install</target>
                        </embedded>
                        <embedded>
                            <groupId>com.test</groupId>
                            <artifactId>test.ui.content</artifactId>
                            <type>zip</type>
                            <target>/apps/test-packages/content/install</target>
                        </embedded>
                        <embedded>
                            <groupId>com.test</groupId>
                            <artifactId>test.ui.config</artifactId>
                            <type>zip</type>
                            <target>/apps/test-packages/application/install</target>
                        </embedded>
                        <!-- AECU Deployment -->
                        <embedded>
                            <groupId>com.test</groupId>
                            <artifactId>test.ui.aecu</artifactId>
                            <type>zip</type>
                            <target>/apps/test-packages/application/install</target>
                        </embedded>
                        <!-- AECU Deployment -->
                        <embedded>
                            <groupId>de.valtech.aecu</groupId>
                            <artifactId>aecu.complete.cloud</artifactId>
                            <type>zip</type>
                            <target>/apps/test-vendor-packages/application/install</target>
                        </embedded>
                    </embeddeds>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <verbose>true</verbose>
                    <failOnError>true</failOnError>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <executions>
                    <execution>
                        <id>auto-clean</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.adobe.aem</groupId>
                <artifactId>aemanalyser-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>aem-analyser</id>
                        <goals>
                            <goal>project-analyse</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!-- ====================================================================== -->
    <!-- P R O F I L E S                                                        -->
    <!-- ====================================================================== -->
    <profiles>
        <profile>
            <id>autoInstallSinglePackage</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.day.jcr.vault</groupId>
                        <artifactId>content-package-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>install-package</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                                <configuration>
                                    <targetURL>http://${aem.host}:${aem.port}/crx/packmgr/service.jsp</targetURL>
                                    <failOnError>true</failOnError>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>autoInstallSinglePackagePublish</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.day.jcr.vault</groupId>
                        <artifactId>content-package-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>install-package-publish</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                                <configuration>
                                    <targetURL>http://${aem.publish.host}:${aem.publish.port}/crx/packmgr/service.jsp</targetURL>
                                    <failOnError>true</failOnError>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <!-- ====================================================================== -->
    <!-- D E P E N D E N C I E S                                                -->
    <!-- ====================================================================== -->
    <dependencies>
        <!-- AECU Deployment -->
        <dependency>
            <groupId>de.valtech.aecu</groupId>
            <artifactId>aecu.complete.cloud</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.test</groupId>
            <artifactId>test.ui.apps</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.test</groupId>
            <artifactId>test.ui.content</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.test</groupId>
            <artifactId>test.ui.config</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <!-- AECU Deployment -->
        <dependency>
            <groupId>com.test</groupId>
            <artifactId>test.ui.aecu</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
    </dependencies>
</project>
```

**Comment by gruberrolandvaltech** [comment]
I added some sanity checks in https://github.com/valtech/aem-easy-content-upgrade/commit/50639454241622f58e25680d48c719ef4324fec1
Please reopen if the issue is still existing with version 6.0.1 (to be released soon).
