### ISSUE TITLE
Removing /var/aecu causing repository error

### ISSUE THREAD

**Issue by pun-ky** [valtech/aem-easy-content-upgrade#26]
Imagine that I just removed `/var/aecu` as I am regularly used to be able to remove `/var/classes`

then the following error is occurring:

```
18.09.2018 08:25:22.994 *INFO* [qtp607693070-70] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Loading Hook aecu: Main-Class = de.valtech.aecu.core.installhook.AecuInstallHook
18.09.2018 08:25:22.994 *INFO* [qtp607693070-70] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook aecu registered.
18.09.2018 08:25:22.994 *INFO* [qtp607693070-70] de.valtech.aecu.core.installhook.AecuInstallHook Executing in phase PREPARE
18.09.2018 08:25:22.999 *INFO* [qtp607693070-70] de.valtech.aecu.core.installhook.AecuInstallHook Executing in phase INSTALLED
18.09.2018 08:25:23.134 *WARN* [qtp607693070-70] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook aecu threw package exception. Ignored
org.apache.jackrabbit.vault.packaging.PackageException: de.valtech.aecu.api.service.AecuException: Unable to create /var/aecu
        at de.valtech.aecu.core.installhook.AecuInstallHook.execute(AecuInstallHook.java:113) [de.valtech.aecu.core:1.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.execute(InstallHookProcessorImpl.java:148) [org.apache.jackrabbit.vault:3.1.43.R1816641]
        at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:241) [org.apache.jackrabbit.vault:3.1.43.R1816641]
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:398) [org.apache.jackrabbit.vault:3.1.43.R1816641]
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:357) [org.apache.jackrabbit.vault:3.1.43.R1816641]
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:351) [org.apache.jackrabbit.vault:3.1.43.R1816641]
        at com.day.crx.packaging.impl.J2EEPackageManager.consoleInstall(J2EEPackageManager.java:352) [com.adobe.granite.crx-packagemgr:1.2.54]
        at com.day.crx.packaging.impl.J2EEPackageManager.doPost(J2EEPackageManager.java:190) [com.adobe.granite.crx-packagemgr:1.2.54]
        at com.day.crx.packaging.impl.PackageManagerServlet.doPost(PackageManagerServlet.java:127) [com.adobe.granite.crx-packagemgr:1.2.54]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [org.apache.felix.http.servlet-api:1.1.2]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [org.apache.felix.http.servlet-api:1.1.2]
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:120) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:86) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:328) [org.apache.sling.security:1.1.10]
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:3.4.7.B012]
        at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:308) [com.adobe.granite.license:1.2.6]
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:96) [org.apache.felix.http.sslfilter:1.2.4]
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131) [org.apache.sling.i18n:2.5.10]
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.Dispatcher$1.doFilter(Dispatcher.java:147) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager.invokePreprocessors(WhiteboardManager.java:1000) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:91) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49) [org.apache.felix.http.jetty:3.4.7.B012]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [org.apache.felix.http.servlet-api:1.1.2]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [org.apache.felix.http.jetty:3.4.7.B012]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [org.apache.felix.http.jetty:3.4.7.B012]
        at java.lang.Thread.run(Unknown Source)
Caused by: de.valtech.aecu.api.service.AecuException: Unable to create /var/aecu
        at de.valtech.aecu.core.history.HistoryUtil.createPath(HistoryUtil.java:369) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.history.HistoryUtil.createPath(HistoryUtil.java:362) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.history.HistoryUtil.createPath(HistoryUtil.java:362) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.history.HistoryUtil.createPath(HistoryUtil.java:362) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.history.HistoryUtil.createHistoryEntry(HistoryUtil.java:89) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.service.AecuServiceImpl.createHistoryEntry(AecuServiceImpl.java:216) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.installhook.AecuInstallHook.executeScripts(AecuInstallHook.java:162) [de.valtech.aecu.core:1.4.0]
        at de.valtech.aecu.core.installhook.AecuInstallHook.execute(AecuInstallHook.java:102) [de.valtech.aecu.core:1.4.0]
        ... 51 common frames omitted
Caused by: org.apache.sling.api.resource.PersistenceException: Unable to create node at /var/aecu
        at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:480) [org.apache.sling.jcr.resource:3.0.8]
        at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.create(AuthenticatedResourceProvider.java:182) [org.apache.sling.resourceresolver:1.5.32]
        at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.create(ResourceResolverControl.java:378) [org.apache.sling.resourceresolver:1.5.32]
        at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.create(ResourceResolverImpl.java:1162) [org.apache.sling.resourceresolver:1.5.32]
        at de.valtech.aecu.core.history.HistoryUtil.createPath(HistoryUtil.java:367) [de.valtech.aecu.core:1.4.0]
        ... 58 common frames omitted
Caused by: javax.jcr.AccessDeniedException: Access denied.
        at org.apache.jackrabbit.oak.jcr.security.AccessManager.checkPermissions(AccessManager.java:71) [org.apache.jackrabbit.oak-jcr:1.7.12.R1818664]
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:295) [org.apache.jackrabbit.oak-jcr:1.7.12.R1818664]
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:264) [org.apache.jackrabbit.oak-jcr:1.7.12.R1818664]
        at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:208) [org.apache.jackrabbit.oak-jcr:1.7.12.R1818664]
        at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:112) [org.apache.jackrabbit.oak-jcr:1.7.12.R1818664]
        at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:264) [org.apache.jackrabbit.oak-jcr:1.7.12.R1818664]
        at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:449) [org.apache.sling.jcr.resource:3.0.8]
        ... 62 common frames omitted

```

and I need to reinstall ui.apps package. I am aware that it is an edge case, but my intention is to make this tool more error defensive.

**Comment by gruberrolandvaltech** [comment]
In this case you also deleted the ACL that allows to write the tool in this area. So in this case a reinstall is required.
But we can add this to our health check.

**Comment by pun-ky** [comment]
Sure thx
